<h1>PHP-Day SERPRO Curitiba</h1>
<p>
Data: 31/05/2011 e 01/06/2011 08:00h - 18:00<br/>
Local: SERPRO - Curitiba<br/>
</p>

<h3>Atualizações</h3>

<p><strong>18/03/2011:</strong> Publicação da grade de palestras.</p>

<p><strong>14/03/2011:</strong> Extendido a data do evendo para o dia 01/06.</p>

<p><strong>11/03/2011:</strong> Devido a problemas no calendário de eventos do SERPRO, o evento PHP-Day SERPRO será transferido de 25/05/2011 para 31/05/2011.</p>


<h2 id="grade">Grade - Palestras</h2>
<?=$this->palestrasGrade()?>



<h2 id="grade-minicurso">Grade - Minicursos</h2>

<h3>1º Dia - 31/05</h3>
<table>
    <tbody>
        <tr>
            <td colspan="4"><strong>Manhã</strong></td>
        </tr>
        <tr>
            <td colspan="2"><strong>Sala 1</strong></td>
            <td colspan="2"><strong>Sala 2</strong></td>
        </tr>
        <tr>
            <td>08:00 </td><td>LIVRE</td>
            <td>08:00 </td><td>LIVRE</td>
        </tr>
        <tr>
            <td colspan="4"><strong>Tarde</strong></td>
        </tr>
        <tr>
            <td colspan="2"><strong>Sala 1</strong></td>
            <td colspan="2"><strong>Sala 2</strong></td>
        </tr>
        <tr>
            <td>14:00 </td><td>LIVRE</td>
            <td>14:00 </td><td>LIVRE</td>
        </tr>
    </tbody>
</table>

<h3>2º Dia - 01/06</h3>
<table>
    <tbody>
        <tr>
            <td colspan="4"><strong>Manhã</strong></td>
        </tr>
        <tr>
            <td colspan="2"><strong>Sala 1</strong></td>
            <td colspan="2"><strong>Sala 2</strong></td>
        </tr>
        <tr>
            <td>08:00 </td><td>LIVRE</td>
            <td>08:00 </td><td>LIVRE</td>
        </tr>
        <tr>
            <td colspan="4"><strong>Tarde</strong></td>
        </tr>
        <tr>
            <td colspan="2"><strong>Sala 1</strong></td>
            <td colspan="2"><strong>Sala 2</strong></td>
        </tr>
        <tr>
            <td>14:00-18:00 </td><td>CakePHP: Framework para des. WEB ágil</td>
            <td>14:00-18:00 </td><td>PreparedKata</td>
        </tr>
    </tbody>
</table>





<h2>O Evento</h2>
<img src="img/elephant.png" style="float: right;"/>
<p>O objetivo do evento é promover evento é uma aproximação entre a comunidade PHP e o SERPRO.</p>
<p>Os palestrantes serão ministradas por funcionários do SERPRO e colaboradores da comunidade PHP.</p>
<p>Qualquer pessoa que quiser palestrar, basta enviar um e-mail com a proposta para a organização do evento.</p>
<p>O SERPRO fica na rua Carlos Pioli, 133. Esta rua fica entre a Igreja do Divino Espiríto Santo, na rua Mateus Leme, e o Hipermercado Condor, na rua Nilo Peçanha.</p>
<p>A rua Carlos Pioli está no bairro do Bom Retiro, próxima da divisa com o Centro Cívico.</p>
<p>Serão 8 palestras de 50 min.</p>
<h3>Público-alvo</h3>
<p>desenvolvedores: analistas e programadores, os caras que criam aplicações PHP para usuários finais.</p>
<p>técnicos de infraestrutura: pessoal do centro de dados, rede local e suporte técnico, os caras que tem de criar sistemas para administrar seus ambientes ou precisam automatizar tarefas com scripts.</p>
<h3>Temas</h3>
<p>Abordando assuntos de interesse em crescimento na área de desenvolvimento e padrões de mercado, foram sugeridos alguns temas:</p>
<ul>
<li>Zend Framework</li>
<li>PHP + OpenSocial</li>
<li>Memcached</li>
<li>Wordpress</li>
<li>Programacao php, qual plataforma usar?</li>
<li>PHPUnit</li>
<li>Doctrine</li>
<li>Smarty</li>
<li>Nginx com PHP</li>
<li>Programação Ágil (SCRUM, XP, LEAN, TDD etc)</li>
<li>GIT</li>
<li>Refatoração</li>
<li>Arquitetura de Softwares</li>
<li>Padrões de Projetos</li>
</ul>

<h3>Transmissão ao vivo</h3>

<p>Todas as palestras serão transmitidas via videostreaming. Vamos fazer uma ampla divulgação nos sites de comunidades. Vamos divulgar nas universidades e faculdades locais também.</p>

<p>Videostreaming neste endereço: <a href="http://streaming.serpro.gov.br/cisl" target="blank">http://streaming.serpro.gov.br/cisl</a><br/>
As palestras ficarão gravadas em <a href="http://streaming.serpro.gov.br/cisl/palestras-anteriores.html" target="blank">http://streaming.serpro.gov.br/cisl/palestras-anteriores.html</a></p>



<h3>Envie a sua proposta</h3>

<p>Caso considere-se apto a ministrar uma palestra entre em contato.</p>
<p>Não importa se já tem palestrante sobre o assunto ou se o assunto não esta nesta lista.</p>
<p>Pois criaremos abertura para o assunto, e se o assunto já foi abordado, podemos ter mais palestrantes ou palestras com temas complementares ou diferentes.</p>
<p>O limite é o seu tempo e dedicação.</p>
<p>Colabore</p>


<h3>Maiores Informações</h3>
<p><strong>Contato:</strong> Alexandre F. Martins (zedmaster at gmail.com) e Flavio G. da Silva Lisboa (flavio dot lisboa at serpro dot gov dot br)
</p>
<p><strong>IRC</strong> - Servidor: irc.freenode.net  Canal: <strong>#php-curitiba</strong></p>


<h3>Organização</h3>
<ul>
    <li>Alexandre F. Martins (zedmaster at gmail.com)</li>
    <li>Flavio G. da Silva Lisboa (flavio dot lisboa at serpro dot gov dot br)</li>
    <li>Comitê Regional de Software Livre de Curitiba (CRSL)</li>
</ul>


