
<h3>Atualizações</h3>

<p><strong>17/05/2011:</strong> Atualizações do site: palestras, minicursos e inscrições.</p>

<p><strong>18/03/2011:</strong> Publicação da grade de palestras.</p>

<p><strong>14/03/2011:</strong> Extendido a data do evendo para o dia 01/06.</p>


<h2 id="grade">Grade - Palestras</h2>
<center><p><a href="/user/inscricao">[Inscrição]</a></p></center>
<?=$this->palestrasGrade()?>


<h2 id="grade-minicurso">Grade - Minicursos</h2>
<center><p><a href="/minicurso">[Inscrição]</a></p></center>
<?=$this->minicursoGrade()?>


<h2>O Evento</h2>
<img src="img/elephant.png" style="float: right;"/>
<p>O objetivo do evento é promover uma aproximação entre a comunidade PHP e o SERPRO.</p>
<p>As palestras serão ministradas por funcionários do SERPRO e colaboradores da comunidade PHP.</p>
<p>Qualquer pessoa que quiser palestrar, basta enviar um e-mail com a proposta para a organização do evento.</p>
<p>O SERPRO fica na rua Carlos Pioli, 133. Esta rua fica entre a Igreja do Divino Espirito Santo, na rua Mateus Leme, e o Hipermercado Condor, na rua Nilo Peçanha.</p>
<p>A rua Carlos Pioli está no bairro do Bom Retiro, próxima da divisa com o Centro Cívico.</p>
<p>Serão 8 palestras de 50 min.</p>


<h3>Público-alvo</h3>
<p>Desenvolvedores: analistas e programadores, os caras que criam aplicações PHP para usuários finais.</p>
<p>Técnicos de infraestrutura: pessoal do centro de dados, rede local e suporte técnico, os caras que tem de criar sistemas para administrar seus ambientes ou precisam automatizar tarefas com scripts.</p>


<h3>Temas</h3>
<p>Abordando assuntos de interesse em crescimento na área de desenvolvimento e padrões de mercado, foram sugeridos alguns temas:</p>

<ul>
    <li>Zend Framework</li>
    <li>PHP + OpenSocial</li>
    <li>Wordpress</li>
    <li>Programacao php, qual plataforma usar?</li>
    <li>PHPUnit</li>
    <li>Programação Ágil (SCRUM, XP, LEAN, TDD etc)</li>
    <li>GIT</li>
    <li>Arquitetura de Softwares</li>
    <li>Padrões de Projetos</li>
</ul>


<h3>Transmissão ao vivo</h3>

<p>Todas as palestras serão transmitidas via videostreaming. Vamos fazer uma ampla divulgação nos sites de comunidades. Vamos divulgar nas universidades e faculdades locais também.</p>

<p>Videostreaming neste endereço: <a href="http://streaming.serpro.gov.br/cisl" target="blank">http://streaming.serpro.gov.br/cisl</a><br/>
As palestras ficarão gravadas em <a href="http://streaming.serpro.gov.br/cisl/palestras-anteriores.html" target="blank">http://streaming.serpro.gov.br/cisl/palestras-anteriores.html</a></p>



<h3>Maiores Informações</h3>
<p><strong>Contato:</strong> Alexandre F. Martins (zedmaster at gmail.com) e Flavio G. da Silva Lisboa (flavio dot lisboa at serpro dot gov dot br)
</p>
<p><strong>IRC</strong> - Servidor: irc.freenode.net  Canal: <strong>#php-curitiba</strong></p>


<h3>Organização</h3>
<ul>
    <li>Alexandre F. Martins (zedmaster at gmail.com)</li>
    <li>Flavio G. da Silva Lisboa (flavio dot lisboa at serpro dot gov dot br)</li>
    <li>Comitê Regional de Software Livre de Curitiba (CRSL)</li>
</ul>


