<h2>Local</h2>

<p>O SERPRO fica na rua Carlos Pioli, 133. Esta rua fica entre a Igreja do Divino Espirito Santo, na rua Mateus Leme, e o Hipermercado Condor, na rua Nilo Peçanha.</p>
<p>A rua Carlos Pioli está no bairro do Bom Retiro, próxima da divisa com o Centro Cívico.</p>

<center>
<iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com.br/maps?q=SERPRO+curitiba&amp;hl=pt-BR&amp;sll=-25.410959,-49.272903&amp;sspn=0.038274,0.006295&amp;ie=UTF8&amp;t=h&amp;view=map&amp;cid=5860844741501367265&amp;hq=SERPRO+curitiba&amp;hnear=&amp;ll=-25.410466,-49.272662&amp;spn=0.004652,0.006866&amp;z=17&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com.br/maps?q=SERPRO+curitiba&amp;hl=pt-BR&amp;sll=-25.410959,-49.272903&amp;sspn=0.038274,0.006295&amp;ie=UTF8&amp;t=h&amp;view=map&amp;cid=5860844741501367265&amp;hq=SERPRO+curitiba&amp;hnear=&amp;ll=-25.410466,-49.272662&amp;spn=0.004652,0.006866&amp;z=17&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">Exibir mapa ampliado</a></small>
</center>

<h2>Como chegar de ônibus</h2>

<h3>Saindo da Praça Tiradentes</h3>
<ul>
    <li>Pegue uma das seguintes linhas: Abranches, Água Verde, Mateus Leme, Vila Suíça</li>
    <li>Desça na rua Mateus Leme, antes do cruzamento com a Carlos Pioli (antes do supermercado Mercadorama)</li>
    <li>Vá em frente até o semáforo e atravesse a Mateus Leme.</li>
</ul>


<h3>Saindo da Praça Osório</h3>
<ul>
    <li>Pegue o ônibus Cabral/Osório e desça na rua Nilo Peçanha, em frente ao Hipermercado Condor</li>
    <li>Entre no Condor e saia pela entrada do estacionamento na rua Carlos Pioli. Desça à esquerda.</li>
</ul>

<h3>Saindo da PUC/PR</h3>
<ul>
    <li>Pegue o ônibus Bom Retiro/PUC e desça na rua Nilo Peçanha, em frente ao Hipermercado Condor</li>
    <li>Entre no Condor e saia pela entrada do estacionamento na rua Carlos Pioli. Desça à esquerda.</li>
</ul>

<h3>Saindo do Aeroporto</h3>
<ul>
    <li>Pegue o ônibus Aeroporto (R$ 2,50) e desça na estação tubo Centro Cívico.</li>
    <li>Atravesse a praça Nossa Senhora de Salete.</li>
    <li>Siga direto pela rua Professor Benedito dos Santos e vire à direita na Mateus Leme.</li>
    <li>Vá em frente até o semáforo e atravesse a Mateus Leme.</li>
</ul>

<h3>Saindo da Rodoviária</h3>
<ul>
    <li>Vá até a Praça Baden Powell</li>
    <li>Pegue o ônibus Aeroporto com sentido para o Centro Cívico e desça na estação tubo Centro Cívico.</li>
    <li>Atravesse a praça Nossa Senhora de Salete.</li>
    <li>Siga direto pela rua Professor Benedito dos Santos e vire à direita na Mateus Leme.</li>
    <li>Vá em frente até o semáforo e atravesse a Mateus Leme.</li>
</ul>


<h2>Restaurantes</h2>

<h3>Hipermercados Condor</h3>
<p>Praça de Alimentação - Restaurante Os Doze Cesares</p>

<h3>Restaurante Mello Manias</h3>
<p>Rua Nilo Peçanha, 1000 - São Francisco, Curitiba - PR, 80520-000</p>

<h3>Subway</h3>
<p>Rua Carlos Pioli, 169 - Curitiba - PR, 80520-170</p>

<h3>Restaurante Cantinho do Sabor</h3>
<p>Rua Nilo Peçanha, 849 - Curitiba - PR, 80520-000</p>

<h3>Costelão do Gaúcho</h3>
<p>Rua Mateus Leme, 2167 - Curitiba - PR, 80530-010</p>

<h3>Muqifo</h3>
<p>Mateus Leme, 1736 - Curitiba - PR, 80530-010</p>

<h3>Restaurante La Rampa</h3>
<p>Rua Nilo Peçanha, 1293 - Bom Retiro, Curitiba - PR, 80520-000</p>

<h3>Restaurante Costelão 1500</h3>
<p>Rua Com Lustoza Andrade, 513 - Centro Cívico, Curitiba - PR, 80520-350</p>


<h2>Hoteis</h2>


<h3>Flat Versailles</h3>
<p>Rua Wellington Oliveira Vianna, 70 - Ahú</p>
<p>Curitiba - PR, 80530-350</p>

<p><a href="http://maps.google.com.br/">Mapa</a></p>
<p>(0xx)41 3254-4466</p>


<h3>Flexy Centro Cívico Hotel</h3>
<p>Rua Dep Mário Barros, 1158 - Centro Cívico</p>
<p>Curitiba - PR, 80530-280</p>

<p><a href="http://maps.google.com.br/">Mapa</a></p>
<p>(0xx)41 3250-1500</p>


