<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
<title>PHP-Day - SERPRO - Curitiba</title>
<style>

body, td, div, p
{
	font-family: Verdana, Arial, Helvetica, Sans-Serif;
	font-size: 12px;
}

body
{
	background-color: #666699;
	background-color: #9999CC;
}

#content
{
	background-color: #EEEEEE;
	width: 778px;
	margin-left: auto;
	margin-right: auto;
}

#content h1
{
	background-color: #666699;
	color: white;
	padding: 5px;
}

#content h2
{
	background-color: #666699;
	color: white;
	text-align: center;
	padding: 5px;
}

#content h3
{
	background-color: #D3D3D3;
	color: black;
	padding: 5px;
	border-bottom: 1px solid black;
}

#content p
{
	padding-left: 15px;
	padding-right: 15px;
}



#nav-menu 
{
    background-color: #666699;
    display: table;
    width: 100%;
}

#nav-menu ul
{
    list-style: none;
    padding: 0;
    margin: 0;
} 

#nav-menu li
{
    float: left;
    margin: 0 0.15em;
} 

#nav-menu li a
{
    background: url(background.gif) #666699 bottom left repeat-x;
    height: 2em;
    line-height: 2em;
    float: left;
    width: 9em;
    display: block;
    border: 0.0em solid #dcdce9;
    font-size: 1em;
    font-weight: bold;
    color: #FFFFFF;
    text-decoration: none;
    text-align: center;
} 

#nav-menu li a:hover
{
    background-color: #EEEEEE;
    color: #666699;
}

.titulo
{
    background-color: #666699;
    color: white;
    padding-bottom: 5px;
    padding-left: 5px;
    padding-right: 5px;
    padding-top: 5px;
    display: block;
    font-size: 2em;
    font-weight: bold;
    margin-bottom: 0.67em;
    margin-left: 0;
    margin-right: 0;
    margin-top: 0.67em;
}

</style>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22398422-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>

</head>
<body>
<div id="content">

<div id="nav-menu">
    <ul>
        <dd><span class="titulo">PHP-Day SERPRO Curitiba</span></dd>
        <li><a href="/">Início</a></li>
        <li><a href="/palestra">Palestras</a></li>
        <li><a href="/minicurso">Mini-Cursos</a></li>
        <li><a href="/user/inscricao">Inscrição</a></li>
        <li><a href="/index/local">Local</a></li>
    </ul>
</div> 

<p>
Data: <strong>31/05/2011</strong> e <strong>01/06/2011</strong> 08:00h - 18:00<br/>
Local: SERPRO - Curitiba<br/>
</p>




<?php echo $this->layout()->content; ?>


</div>
</body>
</html>
