<h2>Inscrição</h2>

<p>Informamos que a inscrição é gratuíta.<p>
<p>Será emitido um certiticado de participação para as pessoas que assinarem a lista de presença.<p>
<p>O certificado será enviado no seu e-mail.</p>

<h3><?=$this->msg?></h3>

<?=$this->form?>


<p>
    <a href="/user/cadastro">Não tenho chave.</a><br/>
    <a href="/palestra">Palestras.</a><br/>
    <a href="/minicurso">Mini Cursos.</a>
</p>
